controller_list:
  - name: fake_ur_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - egh_gripper_finger_left_joint
initial:  # Define initial robot poses.
  - group: ur_manipulator
    pose: home
  - group: gripper
    pose: gripper_close